config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases
  get '/work_basic_edit', to: 'attendances#work_basic_edit'
  get '/working_now', to: 'attendances#working_now'
  
  resources :users do
    collection { post :import }
    member do
      
    end
    get 'attendances/edit'
 
    resources :attendances do
      collection { patch :edit_confirmation
                   post :update_waiting
                   get :edit_confirm
                   get :attendance_log
                   delete :attendance_log_delete
                   
                   post :overwork_confirm_update
                   get :overwork_confirm
                   patch :update
                   get :month_confirmation
                   patch :month_confirmation_update
                   post :month_confirmation_create
      }
      member do
        get :overwork
        post :overwork_update
      end
    end
  end
  

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  attr_accessor :ok_flag


  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid, unless: -> { validation_context == :hoge }
  validate :after_finished_at_is_invalid_without_a_started_at
  validate :after_started_at_than_finished_at_fast_if_invalid
  
  
 
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if (started_at > finished_at) && (tommorow == "0")
    end
  end
  
  def after_finished_at_is_invalid_without_a_started_at
    errors.add(:after_started_at, "が必要です") if after_started_at.blank? && after_finished_at.present?
  end

  def after_started_at_than_finished_at_fast_if_invalid
    if after_started_at.present? && after_finished_at.present?
    errors.add(:after_started_at, "より早い退勤時間は無効です") if after_started_at > after_finished_at && (tommorow_flag == "0")
    end
  end
  



  


  def self.search(search)

    if search
      where(worked_on: search.in_time_zone.all_month)
    else
      all
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_one_month, except: [:working_now, :work_basic_edit, :update_waiting]
  before_action :set_user, only:[:create, :attendance_log, :month_confirmation_create, :attendance_log_delete, :edit, :update_waiting, :overwork, :overwork_update, :month_confirmation_update]
  before_action :no_access_admin, only: [:new, :create, :edit, :update_waiting]
  
  before_action :logged_in_user

  before_action :correct_user, only: [:create, :attendance_log, :month_confirmation_create, :attendance_log_delete, :edit, :update_waiting, :overwork, :overwork_update, :month_confirmation_update]
  before_action :admin_user, only: [:working_now, :work_basic_edit]
  before_action :superior_user, only: [:edit_confirm, :update, :overwork_confirm, :overwork_confirm_update, :month_confirmation, :month_confirmation_update]
  before_action :set_select_who_consent, only: [:edit, :update_waiting]


  def new #勤怠一覧画面-

      who_consent_month_confirm = @attendances.pluck(:month_work_who_consent).uniq
      who_consent_edit_confirm = @attendances.pluck(:who_consent).uniq
      who_consent = who_consent_month_confirm.push(who_consent_edit_confirm)
      who = who_consent.flatten!
      who_uniq = who.uniq.map(&:to_i)
  
  
   @user = User.find(params[:user_id])
   @attendance_month_work = @user.attendances.new
   
   
   if params[:format].present? && (!params[:format] == "work_view") && who_uniq.include?(current_user.id)

     respond_to do |format|
       format.csv do
         send_data render_to_string, filename: "attendances.csv", type: :csv
         
       end
     end
    
   elsif params[:format].nil?
     unless current_user?(@user)
       flash[:danger] = "編集権限がありません"
       redirect_to(root_url)
       
     end
   end
   
   
  end
  

  
  def create #勤怠一覧画面 「出勤」「退勤」ボタン押下時処理
    @user = User.find(params[:user_id])
    @today = Date.current
    @attendance = @user.attendances.find_by(worked_on: params[:dayid])
    
      
    if @attendance.started_at.nil? 
      if @attendance.update_attribute(:started_at, Time.current)
        flash.now[:success] = "おはようございます"
        redirect_to new_user_attendance_path @user
      else
        flash[:danger] = "出勤登録失敗"
        render :new
      end
      
    elsif @attendance.finished_at.nil?
     
      started_at_check = @attendance.started_at
      started_at_range = started_at_check + 1.days
      tommorow_end_of_day = started_at_range.end_of_day
      tommorow_beginning_of_day = tommorow_end_of_day.beginning_of_day
      
      today_end_of_day = @attendance.started_at.end_of_day
      today_beginning_of_day = today_end_of_day.beginning_of_day
      
      if Time.current.between?(today_beginning_of_day,today_end_of_day)
        @attendance.tommorow = "0"
        
        if @attendance.update_attribute(:finished_at, Time.current)
          flash[:success] = "おつかれさまでした"
          redirect_to new_user_attendance_path @user
        else
          flash[:danger] = "退勤登録失敗1"
          render :new
        end
        
      elsif Time.current.between?(tommorow_beginning_of_day,tommorow_end_of_day)
        @attendance.tommorow = "1"
        
        if @attendance.update_attribute(:finished_at, Time.current)
          
          flash[:success] = "おつかれさまでした"
          redirect_to new_user_attendance_path @user
        else
          flash[:danger] = "退勤登録失敗2"
          render :new
        end
        
      else
        flash[:danger] = "退勤登録に失敗しました。出社日時の翌日までの範囲が有効です。編集画面で正しい退勤時間を登録してください。"
        render :new
      end
    
    end
    
  end
  
  
  def month_confirmation_create #勤怠一覧画面 右下 1ヶ月分の勤怠申請ボタン 押下時処理
    if params[:attendance][:month_work_who_consent].present?
      @user = User.find(params[:user_id])
      first_day = params[:dayid]
      first_day = first_day.to_date
       
      last_day = first_day.end_of_month
      attendance_month = @user.attendances.where(worked_on: first_day..last_day)
      
      attendance_month.each do |item|
        attendance = Attendance.find_by(id: item.id)
    
        attendance[:month_work_who_consent] = params[:attendance][:month_work_who_consent]
        attendance[:month_work] = 0
     
        attendance.save
      end
      flash[:success] = "1ヶ月分勤怠の承認申請を送信しました。"
      redirect_to new_user_attendance_path and return
    else
          flash[:danger] = "1ヶ月分勤怠の承認申請を送信できませんでした。"
          render :new
    end
      

    
  end
  

  
  def edit #勤怠編集画面
    @attendance = @user.attendances.find_by(user_id: current_user.id)
    @user = User.find(params[:user_id])
  end
  
  def set_select_who_consent
    @select_attendance = User.where(superior: true).where.not(id: current_user.id).where.not(admin: true)
  end
  

 

  
  def update_waiting # 勤怠編集画面　送信処理
       ActiveRecord::Base.transaction do
          @user = User.find(params[:user_id])
      
          attendance_edit_params.each do |key, item|
          
            if item[:who_consent].present? && item["after_started_at(4i)"].present? && item["after_started_at(5i)"].present? && item["after_finished_at(4i)"].present? && item["after_finished_at(5i)"].present?
              @attendance = Attendance.find(key)
    
                    year = @attendance[:worked_on].year
                    month = @attendance[:worked_on].month
                    day = @attendance.worked_on.day
                    
                    at_after_started_at = Time.new(year.to_i, month.to_i, day.to_i, item["after_started_at(4i)"].to_i, item["after_started_at(5i)"].to_i)
                    at_after_finished_at = Time.new(year.to_i, month.to_i, day.to_i, item["after_finished_at(4i)"].to_i, item["after_finished_at(5i)"].to_i)
                    
                    at_after_started_at = nil if item["after_started_at(5i)"].blank?
                    at_after_finished_at = nil if item["after_finished_at(5i)"].blank?
                    
                    @attendance[:after_started_at] = at_after_started_at
                    @attendance[:after_finished_at] = at_after_finished_at
                    
                    @attendance.request_type_before_copy = @attendance.request_type
                    @attendance.request_status_before_copy = @attendance.request_status
                    @attendance.request_at_before_copy = @attendance.request_at

              unless (@attendance[:started_at] == @attendance[:after_started_at]) && (@attendance[:finished_at] == @attendance[:after_finished_at])
             
                
                    @attendance[:request_at] = Time.current
                   
                    @attendance[:request_type] = 1
                    @attendance[:request_status] = 0
                  
                    @attendance[:before_started_at] = @attendance[:started_at]
                    @attendance[:before_finished_at] = @attendance[:finished_at]
                 
                    @attendance[:who_consent] = item[:who_consent]
                
                    @attendance[:tommorow_flag] = item[:tommorow_flag]
                    @attendance[:note_temporary] = item[:note_temporary]
             
                    @attendance.save!
                   
              end
              
            elsif item[:who_consent].nil? && item["after_started_at(4i)"].present? && item["after_started_at(5i)"].present? && item["after_finished_at(4i)"].present? && item["after_finished_at(5i)"].present?
                  
                  flash.now[:danger] = "指示者を選択してください"
                  raise    
            elsif item[:who_consent].present? && item["after_started_at(4i)"].nil? || item["after_started_at(5i)"].nil? || item["after_finished_at(4i)"].nil? || item["after_finished_at(5i)"].nil?
                  
                  flash.now[:danger] = "指示者が選択されていますが、出社時間or退社時間に不備があります。"
                  raise
            elsif item[:who_consent].nil? && item["after_started_at(4i)"].present? || item["after_started_at(5i)"].present? || item["after_finished_at(4i)"].present? || item["after_finished_at(5i)"].present?
                  
                  flash.now[:danger] = "指示者が選択されていますが、出社時間or退社時間に不備があります。"
                  raise
            end
          end
       end
       flash[:success] = "変更申請を送信しました。承認まで今しばらくお待ちください。"
       redirect_to user_attendances_edit_path
  rescue ActiveRecord::RecordInvalid
     flash.now[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
     render :edit
  rescue RuntimeError
     redirect_to user_attendances_edit_path, flash: { danger: "無効な入力データがあったため、登録出来ませんでした。" } and return
  end
  
  
  def edit_confirm #勤怠変更の承認画面
  
    @attendance = Attendance.where(who_consent: current_user.id).where(request_status: 0).where(request_type: 1).to_a
    @attendance_user_id = @attendance.pluck(:user_id)
    @user = User.new
   
    @users = {}
    @attendance_user_id.each do |user_id|
      @user = User.find_by(id: user_id)
      @user_attendance = @user.attendances.where(who_consent: current_user.id).where(request_status: 0).where(request_type: 1).to_a
  
      @users.merge!(user_id => @user_attendance)
    
    end
    

  end
  
  def update #勤怠変更承認時の処理
    ActiveRecord::Base.transaction do
      update_edit_params.each do |id, item|
     
          item[:request_status] = item[:request_status].to_i
          if item[:ok_flag] == "0"
              # 書かない。複数件あったときに変更チェックしてないものはそのままにしたい
          elsif item[:ok_flag] == "1" && item[:request_status] == 1
      
            attendance = Attendance.find_by(id: id)
            @user = User.find_by(id: attendance.user_id)
            @new_attendance = @user.attendances.new
              
                @new_attendance[:started_at] = attendance.after_started_at
                @new_attendance[:finished_at] = attendance.after_finished_at
                @new_attendance[:before_started_at] = attendance.before_started_at
                @new_attendance[:before_finished_at] = attendance.before_finished_at

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def who_name(user_id)

    @user = User.find(user_id)
    return @user.name
  end
  
  def who_request_status(request_status, request_type)
    @status = '*勤怠変更 申請中*' if request_status == 0 && request_type == 1
    @status = '【勤怠変更 承認済み】' if request_status == 1 && request_type == 1
    @status = '【勤怠変更 承認拒否】' if request_status == 2 && request_type == 1
    
    @status = '*残業 申請中*' if request_status == 0 && request_type == 2
    @status = '【残業変更 承認済み】' if request_status == 1 && request_type == 2
    @status = '【残業変更 承認拒否】' if request_status == 2 && request_type == 2
    return @status
  end
  
  def month_who_confirm(who_consent)

    who_consent = who_consent.to_i
    user = User.find(who_consent)
    return user.name
 
  end  
  
  def over24(hour)
    
    hour = hour.to_i
    hour += 24
    return hour
  end
  
  def over24_time_type(time)
  
    hour = time.hour
    min = time.min
    
    hour_i = hour.to_i
    hour_i += 24
    hour_s = hour_i.to_s
    min_s = min.to_s
    
    hour_0 = hour_s.rjust(2, '0')
    min_0 = min_s.rjust(2, '0')
    time = hour_0 + "：" + min_0
    
    return time
  end
  
  
  def month_confirm_count(who_id)

    user_attendance = Attendance.where(month_work_who_consent: who_id).where(month_work: 0) #勤怠情報から条件と一致するレコードを取得
    ua = user_attendance.pluck(:user_id).uniq #取得したレコードの中でuser_idカラムを取得。
    uniq_user = 0
    ua.each do |user_uniq|
      # 3,5それぞれをeachで回す。まずは3
      user_a = User.find(user_uniq)
      uniq_user_month = user_a.attendances.where(month_work_who_consent: who_id).where(month_work: 0)
      #3の全ての勤怠情報の中から、合致するものを抽出する
      u_count = uniq_user_month.pluck(:worked_on).map(&:beginning_of_month).uniq.count
      
      uniq_user += u_count.to_i
      
    end
    # count_attendance = Attendance.where(month_work_who_consent: id).where(month_work: 0)
    # uniq_user = count_attendance.pluck(:user_id).uniq.count

    return uniq_user
  end
  
  def edit_confirm_count(id)
    count = Attendance.where(who_consent: id).where(request_status: 0).where(request_type: 1).count
    return count
  end
  
  def overwork_confirm_count(id)
    count = Attendance.where(who_consent: id).where(request_status: 0).where(request_type: 2).count
    return count
  end
  
  
  def zishazikan(start_time, finish_time, tommorow)
    hour = finish_time.hour - start_time.hour
    min = finish_time.min - start_time.min
    hour = ( hour + 24 ) if tommorow == "1"
    
    if min < 0
      min = min + 60
      hour = hour - 1
    end

    @sum_time = hour.to_s + ":" + format("%02d",min).to_s
  
    return @sum_time

  end
  
  def zaisha(start_time, finish_time, tommorow)
    hour = finish_time.hour - start_time.hour
    min = finish_time.min - start_time.min
    hour = ( hour + 24 ) if tommorow == "1"
    
    if min < 0
      min = min + 60
      hour = hour - 1
    end
    @sum_time = {}
    @sum_time[:hour] = hour
    @sum_time[:min] = min
    
    return @sum_time
  end
  
  def view_sum(hour, min)

    time = hour * 60.0 + min
    sum_time = time / 60.00.to_f
    sum_zero = format("%.2f",sum_time)
    array_time = sum_zero.to_s.split(".")
    
   
    
    string_hour = array_time[0]
    time_min = array_time[1].to_i * 0.60
    time_min_round = time_min.round(0)

    
    @sum_time = string_hour.to_s + ":" + format("%02d",time_min_round).to_s
    
    return @sum_time
  end
  
  
  def zikangai(after_finished_at, user_id, tommorow)

    finished_at = Time.new(2020, 8, 1, after_finished_at.hour, after_finished_at.min, 0, "+09:00")


    if tommorow == "1"
      finished_at = finished_at + 24.hour
    end
    
    user = User.find(user_id)
    designated_work_end_time = Time.new(2020, 8, 1, user.designated_work_end_time.hour, user.designated_work_end_time.min, 0, "+09:00")
    
    
    time = finished_at - designated_work_end_time
    
    sa = Time.at(time).utc.strftime('%X')
   
    return sa.slice(0..4)
  end
 
end

app/views/attendances/_month_confirmation.html.erb
<div class="modal-dialog modal-lg modal-dialog-center" id="modal-overlay">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
   


          <% if @users.present? %>
            <%= form_with(model: @user_new, url: month_confirmation_update_user_attendances_path(current_user.id), local: true, method: :patch) do |f| %>
            
                    <% @users.each do |key, attendances| %>
                    
                       <h2>【<%= who_name(key).to_s %> からの１ヶ月分勤怠申請】</h2>
                        <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                        	<tbody>
                        		<tr>
                        			<th>月</th>
                        			<th>指示確認印</th>
                        			<th class="active">変更</th>
                        			<th>指示確認印</th>
                        		</tr>
                        	    
                        	  
                        	     
                        	      <% attendances.each do |day| %>
                                    <%= f.fields_for "attendances[]", day do |atn| %>
                                        <tr> 
                                			<td><%= atn.hidden_field :month, :value => day.worked_on %><%= day.worked_on.strftime('%-m月') %></td>
                                			<td><%= atn.select :month_work, [['申請中', 0],['承認', 1],['否認', 2],['なし', 8]] %></td>
                                			<td class="active"><%= atn.check_box :ok_flag %></td>
                                			<td><%= link_to '勤怠確認', new_user_attendance_path(key, format: 'work_view', day_id: day.worked_on), class:"btn btn-primary" %></td>
                                        </tr>
                                    <% end %> 
                                <% end %>
                        	</tbody>
                        </table>
                        
                    <% end %>
                <div class="btn-center">
                  <%= f.submit "変更を送信する", class:"btn btn-primary btn-lg" %>
                </div>
            <% end %>
          <% end %>


 
   
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<% @sum_hour = 0 %>
<% @sum_min = 0 %>
<% @at = [] %>
<table class="table table-bordered table-condensed table-hover" id="table-attendances">
	<tbody>
		<tr>
			<td rowspan="2">
				
				<% if params[:format].nil? %>
				<%= link_to "前月へ", new_user_attendance_path(date: @first_day.to_date.prev_month), class:"btn btn-primary" %>
				<% end %>
				　<%= l(@first_day, format: "%Y年%m月") %>　時間管理表　
				<% if params[:format].nil? %>
				<%= link_to "次月へ", new_user_attendance_path(date: @first_day.to_date.next_month), class:"btn btn-primary" %>
				<% end %>
				
				</td>
			<td>指定勤務開始時間：<%= l(@user.designated_work_start_time, format: "%-H:%M") %></td>
			<td colspan="3" rowspan="2">基本時間：<%= l(@user.basic_work_time, format: "%-H:%M") %></td>
			<td rowspan="2">初日：<%= l(@first_day, format: :short) %></td>
		</tr>
		<tr>
			<td>指定勤務終了時間：<%= l(@user.designated_work_end_time, format: "%-H:%M") %></td>
		</tr>
		<tr>
			<td>所属：<%= @user.affiliation %></td>
			<td>氏名：<%= @user.name %></td>
			<td>コード</td>
			<td><%= @user.uid %></td>
			<td>出勤日数：<%= @work_day_count %></td>
			<td>締め：<%= l(@first_day.end_of_month, format: :short) %></td>
		</tr>
	</tbody>
</table>


<% if superior_user?(current_user.id) && now_view_correct_user?(current_user.id) %>
	<div class="attendance_count_border">
		<% @month_confirm_count = month_confirm_count(current_user.id) %>
		<% if @month_confirm_count == 0 %>
			【所属長承認申請のお知らせ】
		<% else %>
			<%= link_to "【所属長承認申請のお知らせ】", month_confirmation_user_attendances_path(@user.id), remote: true, id:"attendance_red" %>
		<% end %>
		<% unless @month_confirm_count == 0 || nil %>
			<span><%= @month_confirm_count %>件の通知があります</span>
		<% end %>
	</div>
	
	<div class="attendance_count_border">
		<% @edit_count = edit_confirm_count(current_user.id) %>
		<% if @edit_count == 0 %>
			【勤怠変更申請のお知らせ】
		<% else %>
			<%= link_to "【勤怠変更申請のお知らせ】 ", edit_confirm_user_attendances_path(@user.id), remote: true, id:"attendance_red" %>
		<% end %>
		<% unless @edit_count == 0 || nil %>
			<span><%= @edit_count %>件の通知があります</span>
		<% end %>
	</div>
	
	<div class="attendance_count_border">
		<% @overwork_count = overwork_confirm_count(current_user.id) %>
		<% if @overwork_count == 0 %>
			【残業申請のお知らせ】
		<% else %>
			<%= link_to "【残業申請のお知らせ】", overwork_confirm_user_attendances_path(@user.id), remote: true, id:"attendance_red" %>
		<% end %>
		<% unless @overwork_count == 0 || nil %>
			<span><%= @overwork_count %>件の通知があります</span>
		<% end %>
	</div>
<% end %>

<% if params[:format].nil? %>
	<div>
		<%= link_to "勤怠編集", user_attendances_edit_path(user_id: @user.id, date: @first_day), class:"btn btn-primary btn-sm" %>
	</div>
	
	<div>
		<%= link_to "勤怠修正ログ(承認済)", attendance_log_user_attendances_path(current_user), class:"btn btn-primary btn-sm" %>
	</div>
	
	<div>
		<%= link_to "CSV出力", new_user_attendance_path(current_user, format: :csv), class:"btn btn-primary btn-sm" %>
	</div>
<% end %>

<br>

	
	
<table class="table table-bordered table-condensed table-hover" id="table-attendances">
	<tbody>
		<tr>
			<% if params[:format].nil? %>
			<th rowspan="3">残業申請</th>
			<% end %>
			<th rowspan="3">日付</th>
			<th rowspan="3">曜日</th>
			<th colspan="8">【実績】</th>
			<th colspan="5">所定勤務時間</th>
		</tr>
		<tr>
			<th colspan="3">出社</th>
			<th colspan="3">退社</th>
			<th rowspan="2">在社時間</th>
			<th rowspan="2">備考</th>
			<th colspan="2">終了予定時間</th>
			<th rowspan="2">時間外時間</th>
			<th rowspan="2">業務処理内容</th>
			<th rowspan="2">指示者確認印</th>
		</tr>
		<tr>
			<th>時</th>
			<th>分</th>
			<th></th>
			<th>時</th>
			<th>分</th>
			<th></th>
			<th>時</th>
			<th>分</th>
		</tr>
	
	<% @attendances.each do |day| %>
			<% if day.only_day == 1 %>
				<% if params[:format].nil? %>
					<td>
						<% if day.request_status == 0  %>
							<%= link_to '残業申請', overwork_user_attendance_path(current_user.id,day.id), remote: true, class:"btn btn-primary disabled" %>
						<% elsif day.request_status == 2 %>
							<%= link_to '残業申請', overwork_user_attendance_path(current_user.id,day.id), remote: true, class:"btn btn-primary" %>
						<% else %>
							<%= link_to '残業申請', overwork_user_attendance_path(current_user.id,day.id), remote: true, class:"btn btn-primary" %>
						<% end %>
						</td>
				<% end %>
					<td><%= l(day.worked_on, format: :short) %></td>
					<td><%= $days_of_the_week[day.worked_on.wday] %></td>
					<td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
					<td><%= l(day.started_at, format: :minut) if day.started_at.present? %></td>
					<td>
					<% if params[:format].nil? %>	
						<% if (Date.current == day.worked_on) && day.started_at.nil? && day.finished_at.nil? %>
						<%= link_to "出勤登録", user_attendances_path(user_id: params[:user_id], dayid: day.worked_on), method: :create %>
						<% end %>
					<% end %>
					</td>
					
					
					<% if day.finished_at.present? && day.tommorow == "0" %>
						<td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
					<% elsif day.finished_at.present? && day.tommorow == "1" %>
						<td><%= over24(day.finished_at.hour) %></td>
					<% else %>
						<td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
					<% end %>
					
					<td><%= l(day.finished_at, format: :minut) if day.finished_at.present? %></td>
					<td>
					<% if params[:format].nil? %>	
						<% if (Date.current == day.worked_on) && day.finished_at.nil? && day.started_at.present? %>
						<%= link_to "退勤登録", user_attendances_path(user_id: params[:user_id], dayid: day.worked_on), method: :create %>
						<% end %>
					<% end %>
					</td>
					<td><%= zishazikan(day.started_at, day.finished_at, day.tommorow) if day.started_at.present? && day.finished_at.present? %></td>
					<td><%= day.note %></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>
					<%= who_name(day.who_consent) if day.who_consent.present? && day.request_status %><br>
						<%= who_request_status(day.request_status, day.request_type) if day.request_status.present? %>
					<% end %>
					</td>
		</tr>

			<% if day.started_at.present? && day.finished_at.present? && day.only_day == 1 %>
			          <% @i = zishazikan(day.started_at, day.finished_at, day.tommorow) %>
			         
			          <% @at = @i.split(":") %>
			          <% @sum_hour += @at[0].to_i %>
			        	<% @sum_min += @at[1].to_i %>
			<% end %>

	<% end %>
		<tr>
		
			<% if params[:format].nil? %>
			<td></td>
			<% end %>
			<td colspan="2"></td>
			<td colspan="6"></td>
			<td><%= view_sum(@sum_hour, @sum_min) %></td>
			<td colspan="5"></td>
			<td>

			<% if params[:format].nil? %>
			
				<% if @attendances.first.month_work == nil %>
						<%= form_with(model: @attendance_month_work, url: month_confirmation_create_user_attendances_path(user_id: current_user.id, dayid: @first_day), local: true, method: :post) do |f| %>
							<div>所属長承認</div>
							<div><%= f.collection_select :month_work_who_consent, User.where(superior: true).where.not(id: current_user.id).where.not(admin: true), :id, :name, {include_blank: '選択' }, :prompt => true %> </div>
							<div><%= f.submit "申請", class:"btn btn-primary" %></div>
						<% end %>
				<% elsif @attendances.first.month_work == 0 %>
					<%= month_who_confirm(@attendances.first.month_work_who_consent) %><br>*申請中*
				<% elsif @attendances.first.month_work == 1 %>
					<%= month_who_confirm(@attendances.first.month_work_who_consent) %><br>所属長承認：承認済み
				<% elsif (@attendances.first.month_work == 2) %>
						<%= form_with(model: @attendance_month_work, url: month_confirmation_create_user_attendances_path(user_id: current_user.id, dayid: @first_day), local: true, method: :post) do |f| %>
							<div>所属長承認</div>
							<div><%= f.collection_select :month_work_who_consent, User.where(superior: true).where.not(id: current_user.id).where.not(admin: true), :id, :name, {include_blank: '選択' }, :prompt => true %> </div>
							<div><%= f.submit "再度申請", class:"btn btn-primary" %></div>
						<% end %>
					<%= month_who_confirm(@attendances.first.month_work_who_consent) %><br>所属長承認：拒否済み
				<% end %>
			<% elsif params[:format].present? && @attendances.first.month_work == 0 %>
				<%= month_who_confirm(@attendances.first.month_work_who_consent) %><br>*申請中*
			<% end %>
			</td>
		</tr>
	
	</tbody>
</table>


<div id="edit-confirm" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="month-confirmation" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="overwork" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="overwork-confirm" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>