config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases
  get '/work_basic_edit', to: 'attendances#work_basic_edit'
  get '/working_now', to: 'attendances#working_now'
  
  resources :users do
    collection { post :import }
    member do
      
    end
    get 'attendances/edit'
 
    resources :attendances do
      collection { patch :edit_confirmation
                   post :update_waiting
                   get :edit_confirm
                   get :attendance_log
                   delete :attendance_log_delete
                   
                   post :overwork_confirm_update
                   get :overwork_confirm
                   patch :update
                   get :month_confirmation
                   patch :month_confirmation_update
                   post :month_confirmation_create
      }
      member do
        get :overwork
        post :overwork_update
      end
    end
  end
  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠A", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top", root_path %></li>
        
        
        
        
        <% if current_user.present? && admin_user?(current_user.id) %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "出勤中社員一覧", working_now_path %></li>
          <li><%= link_to "拠点情報", bases_path %></li>
          <li><%= link_to "基本情報の更新", work_basic_edit_path %></li>
        <% end %>
        
        <% if current_user.present? && !admin_user?(current_user.id) %>
          <li><%= link_to "勤怠一覧", new_user_attendance_path(current_user.id) %></li>
        <% end %>
        
        <% if current_user.present? %>
        
          
          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% end %>
        <% if !current_user.present? %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
        
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>